const tenants = [
  {
    id: "t-1",
    name: "Acme Corporation",
    slug: "acme-corp",
    plan: "Enterprise",
    status: "Active",
    seats: 120,
    adminEmail: "admin@acme.example",
    createdAt: "2023-08-12",
    monthlyRevenue: "$2,400",
  },
  {
    id: "t-2",
    name: "Bluewater Ltd",
    slug: "bluewater",
    plan: "Pro",
    status: "Active",
    seats: 45,
    adminEmail: "ops@bluewater.example",
    createdAt: "2024-01-03",
    monthlyRevenue: "$540",
  },
  {
    id: "t-3",
    name: "Greenfield Co",
    slug: "greenfield",
    plan: "Trial",
    status: "Trial",
    seats: 8,
    adminEmail: "contact@greenfield.example",
    createdAt: "2024-02-01",
    monthlyRevenue: "$0",
  },
  {
    id: "t-4",
    name: "Northbridge Partners",
    slug: "northbridge",
    plan: "Enterprise",
    status: "Suspended",
    seats: 300,
    adminEmail: "admin@northbridge.example",
    createdAt: "2022-11-21",
    monthlyRevenue: "$6,800",
  },
  {
    id: "t-5",
    name: "Summit Labs",
    slug: "summit-labs",
    plan: "Pro",
    status: "Active",
    seats: 22,
    adminEmail: "it@summit.example",
    createdAt: "2023-06-17",
    monthlyRevenue: "$330",
  },
  {
    id: "t-6",
    name: "Harbor Retail",
    slug: "harbor-retail",
    plan: "Basic",
    status: "Delinquent",
    seats: 12,
    adminEmail: "billing@harbor.example",
    createdAt: "2023-09-05",
    monthlyRevenue: "$95",
  },
  {
    id: "t-7",
    name: "Vertex Solutions",
    slug: "vertex-solutions",
    plan: "Pro",
    status: "Active",
    seats: 60,
    adminEmail: "admin@vertex.example",
    createdAt: "2021-12-10",
    monthlyRevenue: "$720",
  },
  {
    id: "t-8",
    name: "Pine & Co",
    slug: "pine-co",
    plan: "Trial",
    status: "Trial",
    seats: 4,
    adminEmail: "hello@pine.example",
    createdAt: "2024-02-10",
    monthlyRevenue: "$0",
  },
];

export default tenants;
